// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

/*
Package discord_gateway is a generated protocol buffer package.

It is generated from these files:
	gateway.proto

It has these top-level messages:
	NilMessage
	EditRoleRequest
	EditRoleResponse
	SendMessageRequest
	UpdateMemberRequest
	UpdateMemberResponse
	GetAllMembersRequest
	GuildObjectRequest
	GetMembersResponse
	GetRoleResponse
	CreateRoleRequest
	CreateRolesResponse
	DeleteRoleRequest
	DeleteRoleResponse
	GetUserRequest
	GetUserResponse
	Role
	Member
	User
	GetMessagesRequest
	Message
	MessageReactions
	Emoji
	MessageEmbed
	MessageEmbedFooter
	MessageEmbedItem
	MessageEmbedProvider
	MessageEmbedAuthor
	MessageEmbedField
	MessageAttachment
	GetMessagesResponse
	BulkDeleteMessagesRequest
*/
package discord_gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MemberUpdateOperation int32

const (
	MemberUpdateOperation_ADD_OR_UPDATE_ROLES MemberUpdateOperation = 0
	MemberUpdateOperation_REMOVE_ROLES        MemberUpdateOperation = 1
)

var MemberUpdateOperation_name = map[int32]string{
	0: "ADD_OR_UPDATE_ROLES",
	1: "REMOVE_ROLES",
}
var MemberUpdateOperation_value = map[string]int32{
	"ADD_OR_UPDATE_ROLES": 0,
	"REMOVE_ROLES":        1,
}

func (x MemberUpdateOperation) String() string {
	return proto.EnumName(MemberUpdateOperation_name, int32(x))
}
func (MemberUpdateOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NilMessage struct {
}

func (m *NilMessage) Reset()                    { *m = NilMessage{} }
func (m *NilMessage) String() string            { return proto.CompactTextString(m) }
func (*NilMessage) ProtoMessage()               {}
func (*NilMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EditRoleRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Color    int64  `protobuf:"varint,2,opt,name=Color" json:"Color,omitempty"`
	Perm     int64  `protobuf:"varint,3,opt,name=Perm" json:"Perm,omitempty"`
	Position int64  `protobuf:"varint,4,opt,name=Position" json:"Position,omitempty"`
	Hoist    bool   `protobuf:"varint,5,opt,name=Hoist" json:"Hoist,omitempty"`
	Mention  bool   `protobuf:"varint,6,opt,name=Mention" json:"Mention,omitempty"`
	Managed  bool   `protobuf:"varint,7,opt,name=Managed" json:"Managed,omitempty"`
}

func (m *EditRoleRequest) Reset()                    { *m = EditRoleRequest{} }
func (m *EditRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*EditRoleRequest) ProtoMessage()               {}
func (*EditRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EditRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditRoleRequest) GetColor() int64 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *EditRoleRequest) GetPerm() int64 {
	if m != nil {
		return m.Perm
	}
	return 0
}

func (m *EditRoleRequest) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *EditRoleRequest) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *EditRoleRequest) GetMention() bool {
	if m != nil {
		return m.Mention
	}
	return false
}

func (m *EditRoleRequest) GetManaged() bool {
	if m != nil {
		return m.Managed
	}
	return false
}

type EditRoleResponse struct {
}

func (m *EditRoleResponse) Reset()                    { *m = EditRoleResponse{} }
func (m *EditRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*EditRoleResponse) ProtoMessage()               {}
func (*EditRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SendMessageRequest struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channelId" json:"channelId,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *SendMessageRequest) Reset()                    { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()               {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SendMessageRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateMemberRequest struct {
	Operation MemberUpdateOperation `protobuf:"varint,2,opt,name=Operation,enum=discord.gateway.MemberUpdateOperation" json:"Operation,omitempty"`
	UserId    string                `protobuf:"bytes,3,opt,name=UserId" json:"UserId,omitempty"`
	RoleIds   []string              `protobuf:"bytes,4,rep,name=RoleIds" json:"RoleIds,omitempty"`
}

func (m *UpdateMemberRequest) Reset()                    { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()               {}
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateMemberRequest) GetOperation() MemberUpdateOperation {
	if m != nil {
		return m.Operation
	}
	return MemberUpdateOperation_ADD_OR_UPDATE_ROLES
}

func (m *UpdateMemberRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateMemberRequest) GetRoleIds() []string {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

type UpdateMemberResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
}

func (m *UpdateMemberResponse) Reset()                    { *m = UpdateMemberResponse{} }
func (m *UpdateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberResponse) ProtoMessage()               {}
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateMemberResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateMemberResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAllMembersRequest struct {
	After         string `protobuf:"bytes,2,opt,name=After" json:"After,omitempty"`
	NumberPerPage int32  `protobuf:"varint,3,opt,name=NumberPerPage" json:"NumberPerPage,omitempty"`
}

func (m *GetAllMembersRequest) Reset()                    { *m = GetAllMembersRequest{} }
func (m *GetAllMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllMembersRequest) ProtoMessage()               {}
func (*GetAllMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetAllMembersRequest) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *GetAllMembersRequest) GetNumberPerPage() int32 {
	if m != nil {
		return m.NumberPerPage
	}
	return 0
}

type GuildObjectRequest struct {
}

func (m *GuildObjectRequest) Reset()                    { *m = GuildObjectRequest{} }
func (m *GuildObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*GuildObjectRequest) ProtoMessage()               {}
func (*GuildObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetMembersResponse struct {
	Members []*Member `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
}

func (m *GetMembersResponse) Reset()                    { *m = GetMembersResponse{} }
func (m *GetMembersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMembersResponse) ProtoMessage()               {}
func (*GetMembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type GetRoleResponse struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *GetRoleResponse) Reset()                    { *m = GetRoleResponse{} }
func (m *GetRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRoleResponse) ProtoMessage()               {}
func (*GetRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetRoleResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CreateRoleRequest struct {
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Color       int32  `protobuf:"varint,3,opt,name=Color" json:"Color,omitempty"`
	Hoist       bool   `protobuf:"varint,4,opt,name=Hoist" json:"Hoist,omitempty"`
	Permissions int32  `protobuf:"varint,5,opt,name=Permissions" json:"Permissions,omitempty"`
	Mentionable bool   `protobuf:"varint,6,opt,name=Mentionable" json:"Mentionable,omitempty"`
}

func (m *CreateRoleRequest) Reset()                    { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()               {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoleRequest) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *CreateRoleRequest) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *CreateRoleRequest) GetPermissions() int32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *CreateRoleRequest) GetMentionable() bool {
	if m != nil {
		return m.Mentionable
	}
	return false
}

type CreateRolesResponse struct {
	RoleId string `protobuf:"bytes,1,opt,name=RoleId" json:"RoleId,omitempty"`
}

func (m *CreateRolesResponse) Reset()                    { *m = CreateRolesResponse{} }
func (m *CreateRolesResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateRolesResponse) ProtoMessage()               {}
func (*CreateRolesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateRolesResponse) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type DeleteRoleRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *DeleteRoleRequest) Reset()                    { *m = DeleteRoleRequest{} }
func (m *DeleteRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoleRequest) ProtoMessage()               {}
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DeleteRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteRoleResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *DeleteRoleResponse) Reset()                    { *m = DeleteRoleResponse{} }
func (m *DeleteRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoleResponse) ProtoMessage()               {}
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeleteRoleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Role struct {
	Id          string    `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Managed     bool      `protobuf:"varint,3,opt,name=Managed" json:"Managed,omitempty"`
	Mentionable bool      `protobuf:"varint,4,opt,name=Mentionable" json:"Mentionable,omitempty"`
	Hoist       bool      `protobuf:"varint,5,opt,name=Hoist" json:"Hoist,omitempty"`
	Color       int32     `protobuf:"varint,6,opt,name=Color" json:"Color,omitempty"`
	Position    int32     `protobuf:"varint,7,opt,name=Position" json:"Position,omitempty"`
	Permissions int32     `protobuf:"varint,8,opt,name=Permissions" json:"Permissions,omitempty"`
	Members     []*Member `protobuf:"bytes,9,rep,name=Members" json:"Members,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetManaged() bool {
	if m != nil {
		return m.Managed
	}
	return false
}

func (m *Role) GetMentionable() bool {
	if m != nil {
		return m.Mentionable
	}
	return false
}

func (m *Role) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *Role) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Role) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Role) GetPermissions() int32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *Role) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type Member struct {
	GuildId  string  `protobuf:"bytes,1,opt,name=GuildId" json:"GuildId,omitempty"`
	JoinedAt string  `protobuf:"bytes,2,opt,name=JoinedAt" json:"JoinedAt,omitempty"`
	Nick     string  `protobuf:"bytes,3,opt,name=Nick" json:"Nick,omitempty"`
	Deaf     bool    `protobuf:"varint,4,opt,name=Deaf" json:"Deaf,omitempty"`
	Mute     bool    `protobuf:"varint,5,opt,name=Mute" json:"Mute,omitempty"`
	User     *User   `protobuf:"bytes,6,opt,name=User" json:"User,omitempty"`
	Roles    []*Role `protobuf:"bytes,7,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Member) GetGuildId() string {
	if m != nil {
		return m.GuildId
	}
	return ""
}

func (m *Member) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

func (m *Member) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Member) GetDeaf() bool {
	if m != nil {
		return m.Deaf
	}
	return false
}

func (m *Member) GetMute() bool {
	if m != nil {
		return m.Mute
	}
	return false
}

func (m *Member) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Member) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type User struct {
	Id            string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=Email" json:"Email,omitempty"`
	Username      string `protobuf:"bytes,3,opt,name=Username" json:"Username,omitempty"`
	Avatar        string `protobuf:"bytes,4,opt,name=Avatar" json:"Avatar,omitempty"`
	Discriminator string `protobuf:"bytes,5,opt,name=Discriminator" json:"Discriminator,omitempty"`
	Token         string `protobuf:"bytes,6,opt,name=Token" json:"Token,omitempty"`
	Verified      bool   `protobuf:"varint,7,opt,name=Verified" json:"Verified,omitempty"`
	MFAEnabled    bool   `protobuf:"varint,8,opt,name=MFAEnabled" json:"MFAEnabled,omitempty"`
	Bot           bool   `protobuf:"varint,9,opt,name=Bot" json:"Bot,omitempty"`
	Nick          string `protobuf:"bytes,10,opt,name=Nick" json:"Nick,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetDiscriminator() string {
	if m != nil {
		return m.Discriminator
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetMFAEnabled() bool {
	if m != nil {
		return m.MFAEnabled
	}
	return false
}

func (m *User) GetBot() bool {
	if m != nil {
		return m.Bot
	}
	return false
}

func (m *User) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

type GetMessagesRequest struct {
	ChannelID string `protobuf:"bytes,1,opt,name=ChannelID" json:"ChannelID,omitempty"`
	Limit     int64  `protobuf:"varint,2,opt,name=Limit" json:"Limit,omitempty"`
	BeforeID  string `protobuf:"bytes,3,opt,name=BeforeID" json:"BeforeID,omitempty"`
	AfterID   string `protobuf:"bytes,4,opt,name=AfterID" json:"AfterID,omitempty"`
	AroundID  string `protobuf:"bytes,5,opt,name=AroundID" json:"AroundID,omitempty"`
}

func (m *GetMessagesRequest) Reset()                    { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()               {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetMessagesRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *GetMessagesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetMessagesRequest) GetBeforeID() string {
	if m != nil {
		return m.BeforeID
	}
	return ""
}

func (m *GetMessagesRequest) GetAfterID() string {
	if m != nil {
		return m.AfterID
	}
	return ""
}

func (m *GetMessagesRequest) GetAroundID() string {
	if m != nil {
		return m.AroundID
	}
	return ""
}

type Message struct {
	ID              string               `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	ChannelID       string               `protobuf:"bytes,2,opt,name=ChannelID" json:"ChannelID,omitempty"`
	Content         string               `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
	Timestamp       string               `protobuf:"bytes,4,opt,name=Timestamp" json:"Timestamp,omitempty"`
	EditedTimestamp string               `protobuf:"bytes,5,opt,name=EditedTimestamp" json:"EditedTimestamp,omitempty"`
	MentionRoles    []string             `protobuf:"bytes,6,rep,name=MentionRoles" json:"MentionRoles,omitempty"`
	Tts             bool                 `protobuf:"varint,7,opt,name=Tts" json:"Tts,omitempty"`
	MentionEveryone bool                 `protobuf:"varint,8,opt,name=MentionEveryone" json:"MentionEveryone,omitempty"`
	Author          *User                `protobuf:"bytes,9,opt,name=Author" json:"Author,omitempty"`
	Attachments     []*MessageAttachment `protobuf:"bytes,10,rep,name=Attachments" json:"Attachments,omitempty"`
	Embeds          []*MessageEmbed      `protobuf:"bytes,11,rep,name=Embeds" json:"Embeds,omitempty"`
	Mentions        []*User              `protobuf:"bytes,12,rep,name=Mentions" json:"Mentions,omitempty"`
	Reactions       []*MessageReactions  `protobuf:"bytes,13,rep,name=Reactions" json:"Reactions,omitempty"`
	Type            int64                `protobuf:"varint,14,opt,name=Type" json:"Type,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Message) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Message) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Message) GetEditedTimestamp() string {
	if m != nil {
		return m.EditedTimestamp
	}
	return ""
}

func (m *Message) GetMentionRoles() []string {
	if m != nil {
		return m.MentionRoles
	}
	return nil
}

func (m *Message) GetTts() bool {
	if m != nil {
		return m.Tts
	}
	return false
}

func (m *Message) GetMentionEveryone() bool {
	if m != nil {
		return m.MentionEveryone
	}
	return false
}

func (m *Message) GetAuthor() *User {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Message) GetAttachments() []*MessageAttachment {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *Message) GetEmbeds() []*MessageEmbed {
	if m != nil {
		return m.Embeds
	}
	return nil
}

func (m *Message) GetMentions() []*User {
	if m != nil {
		return m.Mentions
	}
	return nil
}

func (m *Message) GetReactions() []*MessageReactions {
	if m != nil {
		return m.Reactions
	}
	return nil
}

func (m *Message) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type MessageReactions struct {
	Count int64  `protobuf:"varint,1,opt,name=Count" json:"Count,omitempty"`
	Me    bool   `protobuf:"varint,2,opt,name=Me" json:"Me,omitempty"`
	Emoji *Emoji `protobuf:"bytes,3,opt,name=Emoji" json:"Emoji,omitempty"`
}

func (m *MessageReactions) Reset()                    { *m = MessageReactions{} }
func (m *MessageReactions) String() string            { return proto.CompactTextString(m) }
func (*MessageReactions) ProtoMessage()               {}
func (*MessageReactions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *MessageReactions) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MessageReactions) GetMe() bool {
	if m != nil {
		return m.Me
	}
	return false
}

func (m *MessageReactions) GetEmoji() *Emoji {
	if m != nil {
		return m.Emoji
	}
	return nil
}

type Emoji struct {
	ID            string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Roles         []string `protobuf:"bytes,3,rep,name=Roles" json:"Roles,omitempty"`
	Managed       bool     `protobuf:"varint,4,opt,name=Managed" json:"Managed,omitempty"`
	RequireColons bool     `protobuf:"varint,5,opt,name=RequireColons" json:"RequireColons,omitempty"`
	Animated      bool     `protobuf:"varint,6,opt,name=Animated" json:"Animated,omitempty"`
}

func (m *Emoji) Reset()                    { *m = Emoji{} }
func (m *Emoji) String() string            { return proto.CompactTextString(m) }
func (*Emoji) ProtoMessage()               {}
func (*Emoji) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Emoji) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Emoji) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Emoji) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Emoji) GetManaged() bool {
	if m != nil {
		return m.Managed
	}
	return false
}

func (m *Emoji) GetRequireColons() bool {
	if m != nil {
		return m.RequireColons
	}
	return false
}

func (m *Emoji) GetAnimated() bool {
	if m != nil {
		return m.Animated
	}
	return false
}

type MessageEmbed struct {
	URL         string                `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
	Type        string                `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
	Title       string                `protobuf:"bytes,3,opt,name=Title" json:"Title,omitempty"`
	Description string                `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	Timestamp   string                `protobuf:"bytes,5,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Color       int64                 `protobuf:"varint,6,opt,name=Color" json:"Color,omitempty"`
	Footer      *MessageEmbedFooter   `protobuf:"bytes,7,opt,name=Footer" json:"Footer,omitempty"`
	Image       *MessageEmbedItem     `protobuf:"bytes,8,opt,name=Image" json:"Image,omitempty"`
	Thumbnail   *MessageEmbedItem     `protobuf:"bytes,9,opt,name=Thumbnail" json:"Thumbnail,omitempty"`
	Video       *MessageEmbedItem     `protobuf:"bytes,10,opt,name=Video" json:"Video,omitempty"`
	Provider    *MessageEmbedProvider `protobuf:"bytes,11,opt,name=Provider" json:"Provider,omitempty"`
	Author      *MessageEmbedAuthor   `protobuf:"bytes,12,opt,name=Author" json:"Author,omitempty"`
	Fields      []*MessageEmbedField  `protobuf:"bytes,13,rep,name=Fields" json:"Fields,omitempty"`
}

func (m *MessageEmbed) Reset()                    { *m = MessageEmbed{} }
func (m *MessageEmbed) String() string            { return proto.CompactTextString(m) }
func (*MessageEmbed) ProtoMessage()               {}
func (*MessageEmbed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *MessageEmbed) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MessageEmbed) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MessageEmbed) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MessageEmbed) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MessageEmbed) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *MessageEmbed) GetColor() int64 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *MessageEmbed) GetFooter() *MessageEmbedFooter {
	if m != nil {
		return m.Footer
	}
	return nil
}

func (m *MessageEmbed) GetImage() *MessageEmbedItem {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *MessageEmbed) GetThumbnail() *MessageEmbedItem {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *MessageEmbed) GetVideo() *MessageEmbedItem {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *MessageEmbed) GetProvider() *MessageEmbedProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *MessageEmbed) GetAuthor() *MessageEmbedAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *MessageEmbed) GetFields() []*MessageEmbedField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type MessageEmbedFooter struct {
	Text         string `protobuf:"bytes,1,opt,name=Text" json:"Text,omitempty"`
	IconURL      string `protobuf:"bytes,2,opt,name=IconURL" json:"IconURL,omitempty"`
	ProxyIconURL string `protobuf:"bytes,3,opt,name=ProxyIconURL" json:"ProxyIconURL,omitempty"`
}

func (m *MessageEmbedFooter) Reset()                    { *m = MessageEmbedFooter{} }
func (m *MessageEmbedFooter) String() string            { return proto.CompactTextString(m) }
func (*MessageEmbedFooter) ProtoMessage()               {}
func (*MessageEmbedFooter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *MessageEmbedFooter) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageEmbedFooter) GetIconURL() string {
	if m != nil {
		return m.IconURL
	}
	return ""
}

func (m *MessageEmbedFooter) GetProxyIconURL() string {
	if m != nil {
		return m.ProxyIconURL
	}
	return ""
}

type MessageEmbedItem struct {
	URL      string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
	ProxyURL string `protobuf:"bytes,2,opt,name=ProxyURL" json:"ProxyURL,omitempty"`
	Width    int64  `protobuf:"varint,3,opt,name=Width" json:"Width,omitempty"`
	Height   int64  `protobuf:"varint,4,opt,name=Height" json:"Height,omitempty"`
}

func (m *MessageEmbedItem) Reset()                    { *m = MessageEmbedItem{} }
func (m *MessageEmbedItem) String() string            { return proto.CompactTextString(m) }
func (*MessageEmbedItem) ProtoMessage()               {}
func (*MessageEmbedItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *MessageEmbedItem) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MessageEmbedItem) GetProxyURL() string {
	if m != nil {
		return m.ProxyURL
	}
	return ""
}

func (m *MessageEmbedItem) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *MessageEmbedItem) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type MessageEmbedProvider struct {
	URL  string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *MessageEmbedProvider) Reset()                    { *m = MessageEmbedProvider{} }
func (m *MessageEmbedProvider) String() string            { return proto.CompactTextString(m) }
func (*MessageEmbedProvider) ProtoMessage()               {}
func (*MessageEmbedProvider) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *MessageEmbedProvider) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MessageEmbedProvider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MessageEmbedAuthor struct {
	URL          string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	IconURL      string `protobuf:"bytes,3,opt,name=IconURL" json:"IconURL,omitempty"`
	ProxyIconURL string `protobuf:"bytes,4,opt,name=ProxyIconURL" json:"ProxyIconURL,omitempty"`
}

func (m *MessageEmbedAuthor) Reset()                    { *m = MessageEmbedAuthor{} }
func (m *MessageEmbedAuthor) String() string            { return proto.CompactTextString(m) }
func (*MessageEmbedAuthor) ProtoMessage()               {}
func (*MessageEmbedAuthor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *MessageEmbedAuthor) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MessageEmbedAuthor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageEmbedAuthor) GetIconURL() string {
	if m != nil {
		return m.IconURL
	}
	return ""
}

func (m *MessageEmbedAuthor) GetProxyIconURL() string {
	if m != nil {
		return m.ProxyIconURL
	}
	return ""
}

type MessageEmbedField struct {
	Name   string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	Inline bool   `protobuf:"varint,3,opt,name=Inline" json:"Inline,omitempty"`
}

func (m *MessageEmbedField) Reset()                    { *m = MessageEmbedField{} }
func (m *MessageEmbedField) String() string            { return proto.CompactTextString(m) }
func (*MessageEmbedField) ProtoMessage()               {}
func (*MessageEmbedField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *MessageEmbedField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageEmbedField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *MessageEmbedField) GetInline() bool {
	if m != nil {
		return m.Inline
	}
	return false
}

type MessageAttachment struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	URL      string `protobuf:"bytes,2,opt,name=URL" json:"URL,omitempty"`
	ProxyURL string `protobuf:"bytes,3,opt,name=ProxyURL" json:"ProxyURL,omitempty"`
	Filename string `protobuf:"bytes,4,opt,name=Filename" json:"Filename,omitempty"`
	Width    int64  `protobuf:"varint,5,opt,name=Width" json:"Width,omitempty"`
	Height   int64  `protobuf:"varint,6,opt,name=Height" json:"Height,omitempty"`
	Size     int64  `protobuf:"varint,7,opt,name=Size" json:"Size,omitempty"`
}

func (m *MessageAttachment) Reset()                    { *m = MessageAttachment{} }
func (m *MessageAttachment) String() string            { return proto.CompactTextString(m) }
func (*MessageAttachment) ProtoMessage()               {}
func (*MessageAttachment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *MessageAttachment) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MessageAttachment) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MessageAttachment) GetProxyURL() string {
	if m != nil {
		return m.ProxyURL
	}
	return ""
}

func (m *MessageAttachment) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *MessageAttachment) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *MessageAttachment) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *MessageAttachment) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetMessagesResponse struct {
	Messages []*Message `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *GetMessagesResponse) Reset()                    { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()               {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *GetMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type BulkDeleteMessagesRequest struct {
	ChannelID string   `protobuf:"bytes,1,opt,name=ChannelID" json:"ChannelID,omitempty"`
	Messages  []string `protobuf:"bytes,2,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *BulkDeleteMessagesRequest) Reset()                    { *m = BulkDeleteMessagesRequest{} }
func (m *BulkDeleteMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkDeleteMessagesRequest) ProtoMessage()               {}
func (*BulkDeleteMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *BulkDeleteMessagesRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *BulkDeleteMessagesRequest) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*NilMessage)(nil), "discord.gateway.NilMessage")
	proto.RegisterType((*EditRoleRequest)(nil), "discord.gateway.EditRoleRequest")
	proto.RegisterType((*EditRoleResponse)(nil), "discord.gateway.EditRoleResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "discord.gateway.SendMessageRequest")
	proto.RegisterType((*UpdateMemberRequest)(nil), "discord.gateway.UpdateMemberRequest")
	proto.RegisterType((*UpdateMemberResponse)(nil), "discord.gateway.UpdateMemberResponse")
	proto.RegisterType((*GetAllMembersRequest)(nil), "discord.gateway.GetAllMembersRequest")
	proto.RegisterType((*GuildObjectRequest)(nil), "discord.gateway.GuildObjectRequest")
	proto.RegisterType((*GetMembersResponse)(nil), "discord.gateway.GetMembersResponse")
	proto.RegisterType((*GetRoleResponse)(nil), "discord.gateway.GetRoleResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "discord.gateway.CreateRoleRequest")
	proto.RegisterType((*CreateRolesResponse)(nil), "discord.gateway.CreateRolesResponse")
	proto.RegisterType((*DeleteRoleRequest)(nil), "discord.gateway.DeleteRoleRequest")
	proto.RegisterType((*DeleteRoleResponse)(nil), "discord.gateway.DeleteRoleResponse")
	proto.RegisterType((*GetUserRequest)(nil), "discord.gateway.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "discord.gateway.GetUserResponse")
	proto.RegisterType((*Role)(nil), "discord.gateway.Role")
	proto.RegisterType((*Member)(nil), "discord.gateway.Member")
	proto.RegisterType((*User)(nil), "discord.gateway.User")
	proto.RegisterType((*GetMessagesRequest)(nil), "discord.gateway.GetMessagesRequest")
	proto.RegisterType((*Message)(nil), "discord.gateway.Message")
	proto.RegisterType((*MessageReactions)(nil), "discord.gateway.MessageReactions")
	proto.RegisterType((*Emoji)(nil), "discord.gateway.Emoji")
	proto.RegisterType((*MessageEmbed)(nil), "discord.gateway.MessageEmbed")
	proto.RegisterType((*MessageEmbedFooter)(nil), "discord.gateway.MessageEmbedFooter")
	proto.RegisterType((*MessageEmbedItem)(nil), "discord.gateway.MessageEmbedItem")
	proto.RegisterType((*MessageEmbedProvider)(nil), "discord.gateway.MessageEmbedProvider")
	proto.RegisterType((*MessageEmbedAuthor)(nil), "discord.gateway.MessageEmbedAuthor")
	proto.RegisterType((*MessageEmbedField)(nil), "discord.gateway.MessageEmbedField")
	proto.RegisterType((*MessageAttachment)(nil), "discord.gateway.MessageAttachment")
	proto.RegisterType((*GetMessagesResponse)(nil), "discord.gateway.GetMessagesResponse")
	proto.RegisterType((*BulkDeleteMessagesRequest)(nil), "discord.gateway.BulkDeleteMessagesRequest")
	proto.RegisterEnum("discord.gateway.MemberUpdateOperation", MemberUpdateOperation_name, MemberUpdateOperation_value)
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x6f, 0xe4, 0x48,
	0x11, 0xcf, 0xfc, 0x9f, 0xa9, 0x49, 0xb2, 0xd9, 0xde, 0xdc, 0x9e, 0x19, 0xfe, 0x65, 0xfb, 0xf6,
	0x20, 0x1c, 0x5c, 0xa4, 0x5b, 0x40, 0x48, 0x70, 0x02, 0xcd, 0xae, 0x27, 0xb9, 0x39, 0x32, 0x49,
	0xe8, 0xfc, 0x39, 0x84, 0x74, 0x8a, 0x9c, 0x71, 0x27, 0xe9, 0x5b, 0x8f, 0x1d, 0xec, 0x9e, 0x25,
	0xe1, 0x95, 0x67, 0x9e, 0x91, 0x90, 0xf8, 0x08, 0x88, 0x27, 0xbe, 0x05, 0x4f, 0x7c, 0x14, 0x3e,
	0x00, 0x42, 0xd5, 0xdd, 0x6e, 0xdb, 0x63, 0x4f, 0x12, 0xa4, 0x7b, 0xeb, 0x2a, 0x57, 0x75, 0xd7,
	0x9f, 0x5f, 0x57, 0x75, 0x19, 0xd6, 0xae, 0x3c, 0xc9, 0xff, 0xe0, 0xdd, 0xed, 0xdc, 0xc4, 0x91,
	0x8c, 0xc8, 0x13, 0x5f, 0x24, 0xd3, 0x28, 0xf6, 0x77, 0x0c, 0x9b, 0xae, 0x02, 0x1c, 0x88, 0x60,
	0xc2, 0x93, 0xc4, 0xbb, 0xe2, 0xf4, 0x9f, 0x35, 0x78, 0x32, 0xf2, 0x85, 0x64, 0x51, 0xc0, 0x19,
	0xff, 0xfd, 0x9c, 0x27, 0x92, 0x10, 0x68, 0x1e, 0x78, 0x33, 0xee, 0xd4, 0xb6, 0x6a, 0xdb, 0x3d,
	0xa6, 0xd6, 0x64, 0x13, 0x5a, 0x6f, 0xa2, 0x20, 0x8a, 0x9d, 0xfa, 0x56, 0x6d, 0xbb, 0xc1, 0x34,
	0x81, 0x92, 0x47, 0x3c, 0x9e, 0x39, 0x0d, 0xc5, 0x54, 0x6b, 0x32, 0x80, 0xee, 0x51, 0x94, 0x08,
	0x29, 0xa2, 0xd0, 0x69, 0x2a, 0xbe, 0xa5, 0x71, 0x97, 0xcf, 0x22, 0x91, 0x48, 0xa7, 0xb5, 0x55,
	0xdb, 0xee, 0x32, 0x4d, 0x10, 0x07, 0x3a, 0x13, 0x1e, 0x2a, 0x85, 0xb6, 0xe2, 0xa7, 0xa4, 0xfa,
	0xe2, 0x85, 0xde, 0x15, 0xf7, 0x9d, 0x8e, 0xf9, 0xa2, 0x49, 0x4a, 0x60, 0x23, 0x33, 0x3b, 0xb9,
	0x89, 0xc2, 0x84, 0xd3, 0x7d, 0x20, 0xc7, 0x3c, 0xf4, 0x8d, 0x6b, 0xa9, 0x37, 0xdf, 0x82, 0xde,
	0xf4, 0xda, 0x0b, 0x43, 0x1e, 0x8c, 0x7d, 0xe3, 0x52, 0xc6, 0xc0, 0x13, 0x66, 0x5a, 0x5e, 0x79,
	0xd6, 0x63, 0x29, 0x49, 0xff, 0x5c, 0x83, 0x67, 0xa7, 0x37, 0xbe, 0x27, 0xf9, 0x84, 0xcf, 0x2e,
	0x78, 0x9c, 0xee, 0xe7, 0x42, 0xef, 0xf0, 0x86, 0xc7, 0x9e, 0xb2, 0x17, 0x75, 0xd6, 0x5f, 0x7d,
	0x6f, 0x67, 0x21, 0xc8, 0x3b, 0x5a, 0x45, 0xab, 0x5b, 0x69, 0x96, 0x29, 0x92, 0xe7, 0xd0, 0x3e,
	0x4d, 0x78, 0x3c, 0xf6, 0x55, 0xec, 0x7a, 0xcc, 0x50, 0x68, 0x0f, 0xfa, 0x34, 0xf6, 0x13, 0xa7,
	0xb9, 0xd5, 0x40, 0x7b, 0x0c, 0x49, 0x3f, 0x87, 0xcd, 0xa2, 0x39, 0xda, 0x6b, 0xd4, 0x38, 0x9e,
	0x4f, 0xa7, 0x3c, 0x49, 0x94, 0x77, 0x5d, 0x96, 0x92, 0x3a, 0xae, 0x05, 0xdf, 0xd2, 0xac, 0x33,
	0xd8, 0xdc, 0xe3, 0x72, 0x18, 0x04, 0x7a, 0xaf, 0x24, 0xf5, 0x6d, 0x13, 0x5a, 0xc3, 0x4b, 0xc9,
	0x63, 0x23, 0xaf, 0x09, 0xf2, 0x12, 0xd6, 0x0e, 0xe6, 0x28, 0x77, 0xc4, 0xe3, 0x23, 0xdc, 0x0d,
	0x4d, 0x6e, 0xb1, 0x22, 0x93, 0x6e, 0x02, 0xd9, 0x9b, 0x8b, 0xc0, 0x3f, 0xbc, 0xf8, 0x8a, 0x4f,
	0xa5, 0xd9, 0x91, 0xee, 0x01, 0xd9, 0xe3, 0xd2, 0x1e, 0x63, 0x6c, 0xfe, 0x04, 0x2d, 0x53, 0x2c,
	0xa7, 0xb6, 0xd5, 0xd8, 0xee, 0xbf, 0x7a, 0x7f, 0x49, 0x04, 0x59, 0x2a, 0x47, 0x7f, 0x09, 0x4f,
	0xf6, 0x78, 0x21, 0xdf, 0xe4, 0x87, 0xd0, 0x42, 0x3a, 0xdd, 0xe3, 0xbd, 0xd2, 0x1e, 0x4a, 0x5a,
	0xcb, 0xd0, 0xbf, 0xd4, 0xe0, 0xe9, 0x9b, 0x98, 0x7b, 0x92, 0x57, 0x41, 0xbd, 0x5e, 0x05, 0x75,
	0xed, 0xa6, 0x81, 0xba, 0x85, 0x6e, 0x33, 0x0f, 0xdd, 0x2d, 0xe8, 0x23, 0xe8, 0x45, 0x92, 0x88,
	0x28, 0x4c, 0x14, 0xac, 0x5b, 0x2c, 0xcf, 0x42, 0x09, 0x83, 0x66, 0xef, 0x22, 0xe0, 0x06, 0xe0,
	0x79, 0x16, 0xfd, 0x18, 0x9e, 0x65, 0x86, 0x65, 0x31, 0x7a, 0x0e, 0x6d, 0x9d, 0x7a, 0x03, 0x5a,
	0x43, 0xd1, 0xef, 0xc3, 0x53, 0x97, 0x07, 0xbc, 0xda, 0x8f, 0xdc, 0x95, 0xa5, 0x3b, 0x40, 0xf2,
	0x82, 0x0f, 0xc1, 0x85, 0x6e, 0xc3, 0xfa, 0x1e, 0x97, 0x88, 0xc3, 0x74, 0xd7, 0x0c, 0xa4, 0xb5,
	0x3c, 0x48, 0xe9, 0xa7, 0x2a, 0x17, 0x5a, 0xd2, 0x6c, 0xfb, 0x03, 0x68, 0x22, 0xad, 0x04, 0xab,
	0x52, 0xa1, 0x84, 0x95, 0x08, 0xfd, 0x53, 0x1d, 0x9a, 0x68, 0x12, 0x59, 0x87, 0xba, 0xdd, 0xba,
	0x3e, 0xf6, 0x2b, 0x93, 0x91, 0xab, 0x00, 0x8d, 0x42, 0x05, 0x58, 0x0c, 0x6c, 0xb3, 0x14, 0xd8,
	0x25, 0xd5, 0xc6, 0xa6, 0xb7, 0x9d, 0x4f, 0x6f, 0xbe, 0x6a, 0x75, 0xd4, 0x87, 0xac, 0x6a, 0x2d,
	0x24, 0xb9, 0x5b, 0x4e, 0x72, 0x0e, 0xcf, 0xbd, 0x47, 0xe2, 0xf9, 0xdf, 0x35, 0x68, 0xeb, 0x35,
	0xfa, 0xa8, 0x6e, 0x8e, 0x0d, 0x46, 0x4a, 0xa2, 0x55, 0x9f, 0x47, 0x22, 0xe4, 0xfe, 0x50, 0x9a,
	0xa8, 0x58, 0x5a, 0x45, 0x4b, 0x4c, 0xdf, 0x9a, 0xfa, 0xa1, 0xd6, 0xc8, 0x73, 0xb9, 0x77, 0x69,
	0x82, 0xa1, 0xd6, 0xc8, 0x9b, 0xcc, 0x25, 0x37, 0x41, 0x50, 0x6b, 0x9b, 0xad, 0xf6, 0x83, 0xd9,
	0xca, 0x2e, 0x59, 0xe7, 0x11, 0x97, 0xec, 0xbf, 0x35, 0xbd, 0x71, 0x29, 0xb5, 0x9b, 0xd0, 0x1a,
	0xcd, 0x3c, 0x11, 0xa4, 0x85, 0x45, 0x11, 0xe8, 0x1e, 0x4a, 0x87, 0x98, 0x74, 0xed, 0x86, 0xa5,
	0x11, 0x7b, 0xc3, 0x77, 0x9e, 0xf4, 0x62, 0xe5, 0x4c, 0x8f, 0x19, 0x0a, 0x8b, 0x91, 0x2b, 0x92,
	0x69, 0x2c, 0x66, 0x22, 0xf4, 0x64, 0x14, 0x2b, 0xbf, 0x7a, 0xac, 0xc8, 0xc4, 0xf3, 0x4e, 0xa2,
	0xb7, 0x5c, 0x37, 0x94, 0x1e, 0xd3, 0x04, 0x9e, 0x77, 0xc6, 0x63, 0x71, 0x29, 0x6c, 0x3f, 0xb1,
	0x34, 0xf9, 0x0e, 0xc0, 0x64, 0x77, 0x38, 0x52, 0xc8, 0xf1, 0x55, 0x8e, 0xbb, 0x2c, 0xc7, 0x21,
	0x1b, 0xd0, 0x78, 0x1d, 0x49, 0xa7, 0xa7, 0x3e, 0xe0, 0xd2, 0x26, 0x00, 0xb2, 0x04, 0xd0, 0xbf,
	0xd6, 0x4c, 0xbd, 0x53, 0x75, 0x36, 0xc9, 0xf5, 0xa0, 0x37, 0xa6, 0xe5, 0xb8, 0x69, 0x0f, 0xb2,
	0x0c, 0x34, 0x76, 0x5f, 0xcc, 0x84, 0x4c, 0x7b, 0xab, 0x22, 0xd0, 0xd8, 0xd7, 0xfc, 0x32, 0x8a,
	0xf9, 0xd8, 0x4d, 0x83, 0x93, 0xd2, 0x88, 0x18, 0x55, 0x9a, 0xc7, 0xae, 0x89, 0x4e, 0x4a, 0xa2,
	0xd6, 0x30, 0x8e, 0xe6, 0xa1, 0x3f, 0x76, 0x4d, 0x64, 0x2c, 0x4d, 0xff, 0xde, 0xb4, 0x0d, 0x41,
	0x25, 0xc8, 0xb5, 0x09, 0x72, 0x8b, 0x16, 0xd6, 0x17, 0x2d, 0x74, 0xa0, 0xf3, 0x26, 0x0a, 0x25,
	0x0f, 0xa5, 0x31, 0x25, 0x25, 0x51, 0xef, 0x44, 0xcc, 0x78, 0x22, 0xbd, 0xd9, 0x8d, 0xb1, 0x25,
	0x63, 0x90, 0x6d, 0xfd, 0xb8, 0xe0, 0x7e, 0x26, 0xa3, 0x8d, 0x5a, 0x64, 0x13, 0x0a, 0xab, 0xe6,
	0xea, 0x6a, 0xb4, 0xb5, 0x55, 0xf3, 0x2b, 0xf0, 0x30, 0x05, 0x27, 0x32, 0x31, 0x99, 0xc3, 0x25,
	0xee, 0x6f, 0x24, 0x46, 0xef, 0x78, 0x7c, 0x17, 0x85, 0xdc, 0x64, 0x6e, 0x91, 0x4d, 0x3e, 0x86,
	0xf6, 0x70, 0x2e, 0xaf, 0xa3, 0x58, 0x65, 0x70, 0x29, 0xe6, 0x8d, 0x10, 0x71, 0xa1, 0x3f, 0x94,
	0xd2, 0x9b, 0x5e, 0xcf, 0x78, 0x28, 0x13, 0x07, 0x14, 0xf6, 0x69, 0xc5, 0xa5, 0x56, 0xd1, 0xcc,
	0x44, 0x59, 0x5e, 0x8d, 0xfc, 0x14, 0xda, 0xa3, 0xd9, 0x05, 0xf7, 0x13, 0xa7, 0xaf, 0x36, 0xf8,
	0xf6, 0xb2, 0x0d, 0x94, 0x14, 0x33, 0xc2, 0xe4, 0x13, 0xe8, 0x1a, 0xf3, 0x13, 0x67, 0x75, 0xc9,
	0xad, 0x53, 0xd6, 0x5a, 0x31, 0xf2, 0x2b, 0xe8, 0x31, 0xee, 0x4d, 0xb5, 0xce, 0x9a, 0xd2, 0x79,
	0xb1, 0xec, 0x30, 0x2b, 0xc8, 0x32, 0x1d, 0x04, 0xf3, 0xc9, 0xdd, 0x0d, 0x77, 0xd6, 0xf5, 0x4b,
	0x0e, 0xd7, 0xf4, 0x12, 0x36, 0x16, 0x55, 0x74, 0xf5, 0x9c, 0x87, 0x52, 0x41, 0x47, 0xbd, 0x03,
	0xe7, 0xa1, 0x44, 0x34, 0x4d, 0x74, 0xdd, 0xee, 0xb2, 0xfa, 0x84, 0x93, 0x1f, 0xe1, 0x75, 0x8f,
	0xbe, 0x12, 0x0a, 0x2d, 0xfd, 0x57, 0xcf, 0x4b, 0xa6, 0xa8, 0xaf, 0x4c, 0x0b, 0xd1, 0xbf, 0xd5,
	0x8c, 0x78, 0x09, 0x95, 0x4b, 0xda, 0xb3, 0x86, 0x48, 0x43, 0x41, 0x44, 0x13, 0xf9, 0x3e, 0xd1,
	0x2c, 0xf6, 0x89, 0x97, 0xb0, 0x86, 0xd7, 0x50, 0xc4, 0x1c, 0x2b, 0xbd, 0x69, 0xd2, 0x5d, 0x56,
	0x64, 0xaa, 0x7b, 0x13, 0x8a, 0x99, 0x27, 0xb9, 0x6f, 0x7a, 0xb4, 0xa5, 0xe9, 0xbf, 0x9a, 0x08,
	0xce, 0x2c, 0x51, 0x08, 0xc4, 0x53, 0xb6, 0x6f, 0xec, 0xc4, 0xa5, 0x0d, 0x9f, 0x31, 0x14, 0xd7,
	0xaa, 0x06, 0x09, 0x19, 0xa4, 0xa5, 0x4d, 0x13, 0xd8, 0x4c, 0x5c, 0x8e, 0xa5, 0xea, 0xc6, 0xbe,
	0x90, 0x7b, 0x2c, 0xcf, 0x2a, 0x5e, 0xa9, 0xd6, 0xe2, 0x95, 0x2a, 0xb4, 0x2f, 0xfb, 0x10, 0xff,
	0x05, 0xb4, 0x77, 0xa3, 0x08, 0x5f, 0x6e, 0x1d, 0x15, 0xf1, 0x0f, 0xee, 0x45, 0x9a, 0x16, 0x65,
	0x46, 0x85, 0xfc, 0x0c, 0x5a, 0xe3, 0x19, 0xbe, 0xeb, 0xba, 0x4a, 0xf7, 0xc5, 0xbd, 0xba, 0x63,
	0xc9, 0x67, 0x4c, 0xcb, 0x23, 0xea, 0x4e, 0xae, 0xe7, 0xb3, 0x8b, 0x10, 0x2b, 0x7b, 0xef, 0xb1,
	0xca, 0x99, 0x0e, 0x9e, 0x7c, 0x26, 0x7c, 0x1e, 0xa9, 0x1a, 0xfa, 0xb8, 0x93, 0x95, 0x3c, 0x19,
	0x42, 0xf7, 0x28, 0x8e, 0xde, 0x09, 0x9f, 0xc7, 0x4e, 0x5f, 0xe9, 0x7e, 0x78, 0xaf, 0x6e, 0x2a,
	0xcc, 0xac, 0x1a, 0x86, 0xcc, 0x54, 0x84, 0xd5, 0x47, 0x84, 0x4c, 0x8b, 0xda, 0xfa, 0xf0, 0x73,
	0x68, 0xef, 0x0a, 0x1e, 0xf8, 0xe9, 0x65, 0xa3, 0xf7, 0xc7, 0x1b, 0x45, 0x99, 0xd1, 0xa0, 0x97,
	0x40, 0xca, 0xc9, 0x50, 0x08, 0xe2, 0xb7, 0x32, 0x7d, 0xc1, 0xe1, 0x1a, 0x41, 0x3d, 0x9e, 0x46,
	0x21, 0x62, 0xcd, 0x3c, 0xe0, 0x0d, 0x89, 0xe5, 0xf2, 0x28, 0x8e, 0x6e, 0xef, 0xd2, 0xcf, 0x1a,
	0x62, 0x05, 0x1e, 0x0d, 0xed, 0xf5, 0xb5, 0xe1, 0xab, 0x40, 0xee, 0x40, 0x45, 0xf2, 0xf6, 0x2e,
	0x3b, 0xc4, 0xd2, 0x88, 0xb5, 0x2f, 0x84, 0x2f, 0xaf, 0xcd, 0x7c, 0xa7, 0x09, 0xec, 0xcc, 0x9f,
	0x71, 0x71, 0x75, 0x2d, 0xcd, 0x78, 0x67, 0x28, 0xfa, 0x29, 0x6c, 0x56, 0x85, 0xbc, 0xfa, 0xb6,
	0x2c, 0x5e, 0x6b, 0x7a, 0x5b, 0x8c, 0x8a, 0x89, 0xf3, 0xa3, 0x74, 0xf3, 0x71, 0x6a, 0xdc, 0x1f,
	0xa7, 0x66, 0x45, 0x9c, 0x4e, 0xe1, 0x69, 0x29, 0x59, 0xcb, 0x66, 0xe0, 0x33, 0x2f, 0x98, 0xa7,
	0x67, 0x6b, 0x02, 0xc3, 0x31, 0x0e, 0x03, 0x11, 0x72, 0xf3, 0x40, 0x35, 0x14, 0xfd, 0x47, 0xcd,
	0xee, 0x9b, 0xf5, 0x84, 0x52, 0x85, 0x33, 0x0e, 0xd6, 0xab, 0x13, 0xd2, 0x58, 0x48, 0xc8, 0x00,
	0xba, 0xbb, 0x22, 0xe0, 0xea, 0xc1, 0xa4, 0x5d, 0xb1, 0x74, 0x96, 0xac, 0x56, 0x75, 0xb2, 0xda,
	0xf9, 0x64, 0xa1, 0x7f, 0xc7, 0xe2, 0x8f, 0x5c, 0x95, 0x8b, 0x06, 0x53, 0x6b, 0xfa, 0x6b, 0x78,
	0x56, 0x78, 0xbb, 0x98, 0xa7, 0xfd, 0x4f, 0xb0, 0x1d, 0x69, 0x9e, 0x99, 0xb4, 0x9c, 0xa5, 0xad,
	0xc5, 0x4a, 0xd2, 0x53, 0xf8, 0xc6, 0xeb, 0x79, 0xf0, 0x56, 0x4f, 0x20, 0xff, 0xdf, 0x7b, 0x68,
	0x90, 0x3b, 0xb0, 0xae, 0x8a, 0xbc, 0xa5, 0x3f, 0x7a, 0x0d, 0xef, 0x55, 0xce, 0xd6, 0xe4, 0x7d,
	0x78, 0x36, 0x74, 0xdd, 0xf3, 0x43, 0x76, 0x7e, 0x7a, 0xe4, 0x0e, 0x4f, 0x46, 0xe7, 0xec, 0x70,
	0x7f, 0x74, 0xbc, 0xb1, 0x42, 0x36, 0x60, 0x95, 0x8d, 0x26, 0x87, 0x67, 0x29, 0xa7, 0xf6, 0xea,
	0x3f, 0x1d, 0x58, 0x77, 0xb5, 0x03, 0x7b, 0xda, 0x7e, 0xf2, 0x25, 0xac, 0xe6, 0x87, 0x6b, 0xf2,
	0xb2, 0xdc, 0x70, 0xcb, 0xbf, 0x02, 0x06, 0x1f, 0x3e, 0x20, 0x65, 0xfe, 0x4b, 0xac, 0x90, 0x2f,
	0x61, 0xad, 0x30, 0x6f, 0x93, 0xb2, 0x66, 0xd5, 0x3c, 0x3e, 0xf8, 0xa0, 0x4a, 0x6c, 0x61, 0x98,
	0xa6, 0x2b, 0xc4, 0x5f, 0x18, 0xe7, 0x87, 0xc9, 0x71, 0x20, 0xa6, 0xfc, 0x6b, 0x3e, 0xe5, 0x0c,
	0xfa, 0x5a, 0x5d, 0x77, 0xdc, 0x0a, 0xad, 0xd2, 0xf8, 0x3f, 0xd8, 0xaa, 0xda, 0xba, 0xf0, 0xd3,
	0x66, 0x85, 0xfc, 0x16, 0x20, 0x9b, 0x7f, 0x49, 0xb9, 0x92, 0x96, 0xa6, 0xf6, 0xc1, 0xcb, 0x7b,
	0x64, 0xf2, 0x16, 0x7f, 0x01, 0x90, 0x4d, 0xc0, 0x15, 0x3b, 0x97, 0xe6, 0xe8, 0x8a, 0x50, 0x94,
	0x47, 0x68, 0xba, 0x42, 0x7e, 0x03, 0xdd, 0xf4, 0xef, 0x13, 0x29, 0xbb, 0xb8, 0xf0, 0x3f, 0x6d,
	0xf0, 0xe2, 0x1e, 0x09, 0xbb, 0xe5, 0x01, 0x74, 0xcc, 0x4c, 0x4d, 0xbe, 0x5b, 0x15, 0xb4, 0xdc,
	0x5c, 0x5e, 0x1d, 0xd5, 0xfc, 0x38, 0xae, 0x4c, 0xec, 0xe7, 0x7e, 0x86, 0x55, 0x64, 0xab, 0xfc,
	0xab, 0x6c, 0xf0, 0xcd, 0x92, 0x50, 0xee, 0x4f, 0xe1, 0x0a, 0xf9, 0x9d, 0x02, 0x40, 0x7a, 0x15,
	0xc9, 0x12, 0xd8, 0x14, 0x6e, 0x7a, 0x45, 0xaa, 0x2a, 0x4a, 0x0c, 0x5d, 0x21, 0xe7, 0x40, 0xca,
	0xe5, 0x82, 0x7c, 0x54, 0xd2, 0x5e, 0x5a, 0x53, 0x1e, 0x30, 0xfe, 0xa2, 0xad, 0x7e, 0x87, 0xfe,
	0xf8, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x9b, 0xd3, 0x37, 0x1f, 0x15, 0x00, 0x00,
}
