// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

/*
Package discord_gateway is a generated protocol buffer package.

It is generated from these files:
	gateway.proto

It has these top-level messages:
	NilMessage
	EditRoleRequest
	EditRoleResponse
	SendMessageRequest
	UpdateMemberRequest
	UpdateMemberResponse
	GetAllMembersRequest
	GuildObjectRequest
	GetMembersResponse
	GetRoleResponse
	CreateRoleRequest
	CreateRolesResponse
	DeleteRoleRequest
	DeleteRoleResponse
	GetUserRequest
	GetUserResponse
	Role
	Member
	User
*/
package discord_gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MemberUpdateOperation int32

const (
	MemberUpdateOperation_ADD_OR_UPDATE_ROLES MemberUpdateOperation = 0
	MemberUpdateOperation_REMOVE_ROLES        MemberUpdateOperation = 1
)

var MemberUpdateOperation_name = map[int32]string{
	0: "ADD_OR_UPDATE_ROLES",
	1: "REMOVE_ROLES",
}
var MemberUpdateOperation_value = map[string]int32{
	"ADD_OR_UPDATE_ROLES": 0,
	"REMOVE_ROLES":        1,
}

func (x MemberUpdateOperation) String() string {
	return proto.EnumName(MemberUpdateOperation_name, int32(x))
}
func (MemberUpdateOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NilMessage struct {
}

func (m *NilMessage) Reset()                    { *m = NilMessage{} }
func (m *NilMessage) String() string            { return proto.CompactTextString(m) }
func (*NilMessage) ProtoMessage()               {}
func (*NilMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EditRoleRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Color    int64  `protobuf:"varint,2,opt,name=Color" json:"Color,omitempty"`
	Perm     int64  `protobuf:"varint,3,opt,name=Perm" json:"Perm,omitempty"`
	Position int64  `protobuf:"varint,4,opt,name=Position" json:"Position,omitempty"`
	Hoist    bool   `protobuf:"varint,5,opt,name=Hoist" json:"Hoist,omitempty"`
	Mention  bool   `protobuf:"varint,6,opt,name=Mention" json:"Mention,omitempty"`
	Managed  bool   `protobuf:"varint,7,opt,name=Managed" json:"Managed,omitempty"`
}

func (m *EditRoleRequest) Reset()                    { *m = EditRoleRequest{} }
func (m *EditRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*EditRoleRequest) ProtoMessage()               {}
func (*EditRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EditRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditRoleRequest) GetColor() int64 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *EditRoleRequest) GetPerm() int64 {
	if m != nil {
		return m.Perm
	}
	return 0
}

func (m *EditRoleRequest) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *EditRoleRequest) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *EditRoleRequest) GetMention() bool {
	if m != nil {
		return m.Mention
	}
	return false
}

func (m *EditRoleRequest) GetManaged() bool {
	if m != nil {
		return m.Managed
	}
	return false
}

type EditRoleResponse struct {
}

func (m *EditRoleResponse) Reset()                    { *m = EditRoleResponse{} }
func (m *EditRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*EditRoleResponse) ProtoMessage()               {}
func (*EditRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SendMessageRequest struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channelId" json:"channelId,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *SendMessageRequest) Reset()                    { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()               {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SendMessageRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateMemberRequest struct {
	Operation MemberUpdateOperation `protobuf:"varint,2,opt,name=Operation,enum=discord.gateway.MemberUpdateOperation" json:"Operation,omitempty"`
	UserId    string                `protobuf:"bytes,3,opt,name=UserId" json:"UserId,omitempty"`
	RoleIds   []string              `protobuf:"bytes,4,rep,name=RoleIds" json:"RoleIds,omitempty"`
}

func (m *UpdateMemberRequest) Reset()                    { *m = UpdateMemberRequest{} }
func (m *UpdateMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberRequest) ProtoMessage()               {}
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateMemberRequest) GetOperation() MemberUpdateOperation {
	if m != nil {
		return m.Operation
	}
	return MemberUpdateOperation_ADD_OR_UPDATE_ROLES
}

func (m *UpdateMemberRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateMemberRequest) GetRoleIds() []string {
	if m != nil {
		return m.RoleIds
	}
	return nil
}

type UpdateMemberResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
}

func (m *UpdateMemberResponse) Reset()                    { *m = UpdateMemberResponse{} }
func (m *UpdateMemberResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberResponse) ProtoMessage()               {}
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateMemberResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateMemberResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAllMembersRequest struct {
	After         string `protobuf:"bytes,2,opt,name=After" json:"After,omitempty"`
	NumberPerPage int32  `protobuf:"varint,3,opt,name=NumberPerPage" json:"NumberPerPage,omitempty"`
}

func (m *GetAllMembersRequest) Reset()                    { *m = GetAllMembersRequest{} }
func (m *GetAllMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllMembersRequest) ProtoMessage()               {}
func (*GetAllMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetAllMembersRequest) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *GetAllMembersRequest) GetNumberPerPage() int32 {
	if m != nil {
		return m.NumberPerPage
	}
	return 0
}

type GuildObjectRequest struct {
}

func (m *GuildObjectRequest) Reset()                    { *m = GuildObjectRequest{} }
func (m *GuildObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*GuildObjectRequest) ProtoMessage()               {}
func (*GuildObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetMembersResponse struct {
	Members []*Member `protobuf:"bytes,1,rep,name=Members" json:"Members,omitempty"`
}

func (m *GetMembersResponse) Reset()                    { *m = GetMembersResponse{} }
func (m *GetMembersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMembersResponse) ProtoMessage()               {}
func (*GetMembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetMembersResponse) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type GetRoleResponse struct {
	Roles []*Role `protobuf:"bytes,1,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *GetRoleResponse) Reset()                    { *m = GetRoleResponse{} }
func (m *GetRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRoleResponse) ProtoMessage()               {}
func (*GetRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetRoleResponse) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CreateRoleRequest struct {
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Color       int32  `protobuf:"varint,3,opt,name=Color" json:"Color,omitempty"`
	Hoist       bool   `protobuf:"varint,4,opt,name=Hoist" json:"Hoist,omitempty"`
	Permissions int32  `protobuf:"varint,5,opt,name=Permissions" json:"Permissions,omitempty"`
	Mentionable bool   `protobuf:"varint,6,opt,name=Mentionable" json:"Mentionable,omitempty"`
}

func (m *CreateRoleRequest) Reset()                    { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()               {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoleRequest) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *CreateRoleRequest) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *CreateRoleRequest) GetPermissions() int32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *CreateRoleRequest) GetMentionable() bool {
	if m != nil {
		return m.Mentionable
	}
	return false
}

type CreateRolesResponse struct {
	RoleId string `protobuf:"bytes,1,opt,name=RoleId" json:"RoleId,omitempty"`
}

func (m *CreateRolesResponse) Reset()                    { *m = CreateRolesResponse{} }
func (m *CreateRolesResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateRolesResponse) ProtoMessage()               {}
func (*CreateRolesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateRolesResponse) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type DeleteRoleRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *DeleteRoleRequest) Reset()                    { *m = DeleteRoleRequest{} }
func (m *DeleteRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoleRequest) ProtoMessage()               {}
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DeleteRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteRoleResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *DeleteRoleResponse) Reset()                    { *m = DeleteRoleResponse{} }
func (m *DeleteRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoleResponse) ProtoMessage()               {}
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeleteRoleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Role struct {
	Id          string    `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Managed     bool      `protobuf:"varint,3,opt,name=Managed" json:"Managed,omitempty"`
	Mentionable bool      `protobuf:"varint,4,opt,name=Mentionable" json:"Mentionable,omitempty"`
	Hoist       bool      `protobuf:"varint,5,opt,name=Hoist" json:"Hoist,omitempty"`
	Color       int32     `protobuf:"varint,6,opt,name=Color" json:"Color,omitempty"`
	Position    int32     `protobuf:"varint,7,opt,name=Position" json:"Position,omitempty"`
	Permissions int32     `protobuf:"varint,8,opt,name=Permissions" json:"Permissions,omitempty"`
	Members     []*Member `protobuf:"bytes,9,rep,name=Members" json:"Members,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetManaged() bool {
	if m != nil {
		return m.Managed
	}
	return false
}

func (m *Role) GetMentionable() bool {
	if m != nil {
		return m.Mentionable
	}
	return false
}

func (m *Role) GetHoist() bool {
	if m != nil {
		return m.Hoist
	}
	return false
}

func (m *Role) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Role) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Role) GetPermissions() int32 {
	if m != nil {
		return m.Permissions
	}
	return 0
}

func (m *Role) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type Member struct {
	GuildId  string  `protobuf:"bytes,1,opt,name=GuildId" json:"GuildId,omitempty"`
	JoinedAt string  `protobuf:"bytes,2,opt,name=JoinedAt" json:"JoinedAt,omitempty"`
	Nick     string  `protobuf:"bytes,3,opt,name=Nick" json:"Nick,omitempty"`
	Deaf     bool    `protobuf:"varint,4,opt,name=Deaf" json:"Deaf,omitempty"`
	Mute     bool    `protobuf:"varint,5,opt,name=Mute" json:"Mute,omitempty"`
	User     *User   `protobuf:"bytes,6,opt,name=User" json:"User,omitempty"`
	Roles    []*Role `protobuf:"bytes,7,rep,name=Roles" json:"Roles,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Member) GetGuildId() string {
	if m != nil {
		return m.GuildId
	}
	return ""
}

func (m *Member) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

func (m *Member) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Member) GetDeaf() bool {
	if m != nil {
		return m.Deaf
	}
	return false
}

func (m *Member) GetMute() bool {
	if m != nil {
		return m.Mute
	}
	return false
}

func (m *Member) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Member) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type User struct {
	Id            string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Email         string `protobuf:"bytes,2,opt,name=Email" json:"Email,omitempty"`
	Username      string `protobuf:"bytes,3,opt,name=Username" json:"Username,omitempty"`
	Avatar        string `protobuf:"bytes,4,opt,name=Avatar" json:"Avatar,omitempty"`
	Discriminator string `protobuf:"bytes,5,opt,name=Discriminator" json:"Discriminator,omitempty"`
	Token         string `protobuf:"bytes,6,opt,name=Token" json:"Token,omitempty"`
	Verified      bool   `protobuf:"varint,7,opt,name=Verified" json:"Verified,omitempty"`
	MFAEnabled    bool   `protobuf:"varint,8,opt,name=MFAEnabled" json:"MFAEnabled,omitempty"`
	Bot           bool   `protobuf:"varint,9,opt,name=Bot" json:"Bot,omitempty"`
	Nick          string `protobuf:"bytes,10,opt,name=Nick" json:"Nick,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetDiscriminator() string {
	if m != nil {
		return m.Discriminator
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetMFAEnabled() bool {
	if m != nil {
		return m.MFAEnabled
	}
	return false
}

func (m *User) GetBot() bool {
	if m != nil {
		return m.Bot
	}
	return false
}

func (m *User) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func init() {
	proto.RegisterType((*NilMessage)(nil), "discord.gateway.NilMessage")
	proto.RegisterType((*EditRoleRequest)(nil), "discord.gateway.EditRoleRequest")
	proto.RegisterType((*EditRoleResponse)(nil), "discord.gateway.EditRoleResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "discord.gateway.SendMessageRequest")
	proto.RegisterType((*UpdateMemberRequest)(nil), "discord.gateway.UpdateMemberRequest")
	proto.RegisterType((*UpdateMemberResponse)(nil), "discord.gateway.UpdateMemberResponse")
	proto.RegisterType((*GetAllMembersRequest)(nil), "discord.gateway.GetAllMembersRequest")
	proto.RegisterType((*GuildObjectRequest)(nil), "discord.gateway.GuildObjectRequest")
	proto.RegisterType((*GetMembersResponse)(nil), "discord.gateway.GetMembersResponse")
	proto.RegisterType((*GetRoleResponse)(nil), "discord.gateway.GetRoleResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "discord.gateway.CreateRoleRequest")
	proto.RegisterType((*CreateRolesResponse)(nil), "discord.gateway.CreateRolesResponse")
	proto.RegisterType((*DeleteRoleRequest)(nil), "discord.gateway.DeleteRoleRequest")
	proto.RegisterType((*DeleteRoleResponse)(nil), "discord.gateway.DeleteRoleResponse")
	proto.RegisterType((*GetUserRequest)(nil), "discord.gateway.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "discord.gateway.GetUserResponse")
	proto.RegisterType((*Role)(nil), "discord.gateway.Role")
	proto.RegisterType((*Member)(nil), "discord.gateway.Member")
	proto.RegisterType((*User)(nil), "discord.gateway.User")
	proto.RegisterEnum("discord.gateway.MemberUpdateOperation", MemberUpdateOperation_name, MemberUpdateOperation_value)
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5b, 0x73, 0xdb, 0x44,
	0x14, 0xb6, 0x7c, 0xd7, 0xc9, 0xb5, 0x1b, 0xb7, 0xd5, 0x18, 0x06, 0xcc, 0x12, 0xc0, 0xc0, 0xe0,
	0x19, 0xc2, 0x2b, 0xc3, 0x8c, 0x5b, 0x1b, 0x93, 0x4e, 0x1d, 0x9b, 0x4d, 0x13, 0x78, 0xe9, 0x64,
	0x14, 0xeb, 0x24, 0x88, 0xca, 0x92, 0xd1, 0xae, 0x61, 0x78, 0xe6, 0x99, 0x67, 0x7e, 0x49, 0xff,
	0x08, 0x3f, 0x88, 0x61, 0xf6, 0xa2, 0x8b, 0x2d, 0xb5, 0xc9, 0x43, 0xdf, 0xf6, 0x3b, 0xfa, 0xce,
	0xd9, 0x73, 0xd3, 0x39, 0x0b, 0x7b, 0xb7, 0xae, 0xc0, 0x3f, 0xdc, 0x3f, 0x07, 0xab, 0x38, 0x12,
	0x11, 0x39, 0xf0, 0x7c, 0xbe, 0x88, 0x62, 0x6f, 0x60, 0xc4, 0x74, 0x17, 0xe0, 0xcc, 0x0f, 0xa6,
	0xc8, 0xb9, 0x7b, 0x8b, 0xf4, 0xb5, 0x05, 0x07, 0x63, 0xcf, 0x17, 0x2c, 0x0a, 0x90, 0xe1, 0x6f,
	0x6b, 0xe4, 0x82, 0x10, 0xa8, 0x9f, 0xb9, 0x4b, 0x74, 0xac, 0x9e, 0xd5, 0xb7, 0x99, 0x3a, 0x93,
	0x0e, 0x34, 0x9e, 0x46, 0x41, 0x14, 0x3b, 0xd5, 0x9e, 0xd5, 0xaf, 0x31, 0x0d, 0x24, 0x73, 0x8e,
	0xf1, 0xd2, 0xa9, 0x29, 0xa1, 0x3a, 0x93, 0x2e, 0xb4, 0xe7, 0x11, 0xf7, 0x85, 0x1f, 0x85, 0x4e,
	0x5d, 0xc9, 0x53, 0x2c, 0xad, 0xfc, 0x10, 0xf9, 0x5c, 0x38, 0x8d, 0x9e, 0xd5, 0x6f, 0x33, 0x0d,
	0x88, 0x03, 0xad, 0x29, 0x86, 0x4a, 0xa1, 0xa9, 0xe4, 0x09, 0x54, 0x5f, 0xdc, 0xd0, 0xbd, 0x45,
	0xcf, 0x69, 0x99, 0x2f, 0x1a, 0x52, 0x02, 0x87, 0x99, 0xdb, 0x7c, 0x15, 0x85, 0x1c, 0xe9, 0x73,
	0x20, 0xe7, 0x18, 0x7a, 0x26, 0xb4, 0x24, 0x9a, 0xf7, 0xc1, 0x5e, 0xfc, 0xe2, 0x86, 0x21, 0x06,
	0xa7, 0x9e, 0x09, 0x29, 0x13, 0xc8, 0x1b, 0x96, 0x9a, 0xaf, 0x22, 0xb3, 0x59, 0x02, 0xe9, 0xdf,
	0x16, 0x1c, 0x5d, 0xac, 0x3c, 0x57, 0xe0, 0x14, 0x97, 0xd7, 0x18, 0x27, 0xf6, 0x46, 0x60, 0xcf,
	0x56, 0x18, 0xbb, 0xca, 0x5f, 0xa9, 0xb3, 0x7f, 0xf2, 0xe9, 0x60, 0x2b, 0xc9, 0x03, 0xad, 0xa2,
	0xd5, 0x53, 0x36, 0xcb, 0x14, 0xc9, 0x23, 0x68, 0x5e, 0x70, 0x8c, 0x4f, 0x3d, 0x95, 0x3b, 0x9b,
	0x19, 0x24, 0xfd, 0x91, 0x31, 0x9d, 0x7a, 0xdc, 0xa9, 0xf7, 0x6a, 0xd2, 0x1f, 0x03, 0xe9, 0x33,
	0xe8, 0x6c, 0xba, 0xa3, 0xa3, 0x96, 0x1a, 0xe7, 0xeb, 0xc5, 0x02, 0x39, 0x57, 0xd1, 0xb5, 0x59,
	0x02, 0x75, 0x5e, 0x37, 0x62, 0x4b, 0xaa, 0xce, 0xa0, 0x33, 0x41, 0x31, 0x0c, 0x02, 0x6d, 0x8b,
	0x27, 0xb1, 0x75, 0xa0, 0x31, 0xbc, 0x11, 0x18, 0x1b, 0xbe, 0x06, 0xe4, 0x18, 0xf6, 0xce, 0xd6,
	0x92, 0x37, 0xc7, 0x78, 0x2e, 0xad, 0x49, 0x97, 0x1b, 0x6c, 0x53, 0x48, 0x3b, 0x40, 0x26, 0x6b,
	0x3f, 0xf0, 0x66, 0xd7, 0xbf, 0xe2, 0x42, 0x18, 0x8b, 0x74, 0x02, 0x64, 0x82, 0x22, 0xbd, 0xc6,
	0xf8, 0xfc, 0xb5, 0xf4, 0x4c, 0x89, 0x1c, 0xab, 0x57, 0xeb, 0xef, 0x9c, 0x3c, 0x7e, 0x43, 0x06,
	0x59, 0xc2, 0xa3, 0xdf, 0xc1, 0xc1, 0x04, 0x37, 0xea, 0x4d, 0xbe, 0x84, 0x86, 0xc4, 0x89, 0x8d,
	0x87, 0x05, 0x1b, 0x8a, 0xad, 0x39, 0xf4, 0x1f, 0x0b, 0x1e, 0x3c, 0x8d, 0xd1, 0x15, 0x58, 0xd6,
	0xea, 0xd5, 0xb2, 0x56, 0xd7, 0x61, 0x9a, 0x56, 0x4f, 0x5b, 0xb7, 0x9e, 0x6f, 0xdd, 0x1e, 0xec,
	0xc8, 0xa6, 0xf7, 0x39, 0xf7, 0xa3, 0x90, 0xab, 0xb6, 0x6e, 0xb0, 0xbc, 0x48, 0x32, 0x4c, 0x37,
	0xbb, 0xd7, 0x01, 0x9a, 0x06, 0xcf, 0x8b, 0xe8, 0x57, 0x70, 0x94, 0x39, 0x96, 0xe5, 0xe8, 0x11,
	0x34, 0x75, 0xe9, 0x4d, 0xd3, 0x1a, 0x44, 0x3f, 0x83, 0x07, 0x23, 0x0c, 0xb0, 0x3c, 0x8e, 0xdc,
	0x2f, 0x4b, 0x07, 0x40, 0xf2, 0xc4, 0xbb, 0xda, 0x85, 0xf6, 0x61, 0x7f, 0x82, 0x42, 0xf6, 0x61,
	0x62, 0x35, 0x6b, 0x52, 0x2b, 0xdf, 0xa4, 0xf4, 0x5b, 0x55, 0x0b, 0xcd, 0x34, 0x66, 0x3f, 0x87,
	0xba, 0xc4, 0x8a, 0x58, 0x56, 0x0a, 0x45, 0x56, 0x14, 0xfa, 0x57, 0x15, 0xea, 0xd2, 0x25, 0xb2,
	0x0f, 0xd5, 0xd4, 0x74, 0xf5, 0xd4, 0x2b, 0x2d, 0x46, 0x6e, 0x02, 0xd4, 0x36, 0x26, 0xc0, 0x76,
	0x62, 0xeb, 0x85, 0xc4, 0xbe, 0x61, 0xda, 0xa4, 0xe5, 0x6d, 0xe6, 0xcb, 0x9b, 0x9f, 0x5a, 0x2d,
	0xf5, 0x21, 0x9b, 0x5a, 0x5b, 0x45, 0x6e, 0x17, 0x8b, 0x9c, 0xeb, 0x67, 0xfb, 0x9e, 0xfd, 0xfc,
	0xaf, 0x05, 0x4d, 0x7d, 0x96, 0x31, 0xaa, 0x3f, 0x27, 0x4d, 0x46, 0x02, 0xa5, 0x57, 0xcf, 0x22,
	0x3f, 0x44, 0x6f, 0x28, 0x4c, 0x56, 0x52, 0xac, 0xb2, 0xe5, 0x2f, 0x5e, 0x99, 0xf9, 0xa1, 0xce,
	0x52, 0x36, 0x42, 0xf7, 0xc6, 0x24, 0x43, 0x9d, 0xa5, 0x6c, 0xba, 0x16, 0x68, 0x92, 0xa0, 0xce,
	0x69, 0xb5, 0x9a, 0x77, 0x56, 0x2b, 0xfb, 0xc9, 0x5a, 0xf7, 0xf8, 0xc9, 0xfe, 0xb3, 0xb4, 0xe1,
	0x42, 0x69, 0x3b, 0xd0, 0x18, 0x2f, 0x5d, 0x3f, 0x48, 0x06, 0x8b, 0x02, 0x32, 0x3c, 0xc9, 0x0e,
	0x65, 0xd1, 0x75, 0x18, 0x29, 0x96, 0xbd, 0x37, 0xfc, 0xdd, 0x15, 0x6e, 0xac, 0x82, 0xb1, 0x99,
	0x41, 0x72, 0x18, 0x8d, 0x7c, 0xbe, 0x88, 0xfd, 0xa5, 0x1f, 0xba, 0x22, 0x8a, 0x55, 0x5c, 0x36,
	0xdb, 0x14, 0xca, 0xfb, 0x5e, 0x44, 0xaf, 0x50, 0x2f, 0x14, 0x9b, 0x69, 0x20, 0xef, 0xbb, 0xc4,
	0xd8, 0xbf, 0xf1, 0xd3, 0x7d, 0x92, 0x62, 0xf2, 0x01, 0xc0, 0xf4, 0xfb, 0xe1, 0x58, 0x75, 0x8e,
	0xa7, 0x6a, 0xdc, 0x66, 0x39, 0x09, 0x39, 0x84, 0xda, 0x93, 0x48, 0x38, 0xb6, 0xfa, 0x20, 0x8f,
	0x69, 0x01, 0x20, 0x2b, 0xc0, 0x17, 0x4f, 0xe0, 0x61, 0xe9, 0xe8, 0x27, 0x8f, 0xe1, 0x68, 0x38,
	0x1a, 0x5d, 0xcd, 0xd8, 0xd5, 0xc5, 0x7c, 0x34, 0x7c, 0x31, 0xbe, 0x62, 0xb3, 0xe7, 0xe3, 0xf3,
	0xc3, 0x0a, 0x39, 0x84, 0x5d, 0x36, 0x9e, 0xce, 0x2e, 0x13, 0x89, 0x75, 0xf2, 0xba, 0x09, 0xfb,
	0x23, 0x9d, 0xe4, 0x89, 0xce, 0x31, 0x79, 0x09, 0xbb, 0xf9, 0xd9, 0x4f, 0x8e, 0x8b, 0x15, 0x2b,
	0x6e, 0xaa, 0xee, 0x27, 0x77, 0xb0, 0xcc, 0xda, 0xac, 0x90, 0x97, 0xb0, 0xb7, 0xb1, 0x0e, 0x48,
	0x51, 0xb3, 0x6c, 0x5d, 0x74, 0x3f, 0x2e, 0xa3, 0x6d, 0xcd, 0x7a, 0x5a, 0x21, 0xde, 0xd6, 0xb6,
	0x19, 0xf2, 0xf3, 0xc0, 0x5f, 0xe0, 0x3b, 0xbe, 0xe5, 0x12, 0x76, 0xb4, 0xba, 0x6a, 0x45, 0x52,
	0xa2, 0x55, 0xd8, 0x4e, 0xdd, 0x5e, 0x99, 0xe9, 0x8d, 0x37, 0x45, 0x85, 0xfc, 0x0c, 0x90, 0x8d,
	0x67, 0x42, 0x0b, 0x1a, 0x85, 0xa5, 0xd2, 0x3d, 0x7e, 0x0b, 0x27, 0xef, 0xf1, 0x4f, 0x00, 0xd9,
	0x80, 0x2e, 0xb1, 0x5c, 0x18, 0xf3, 0x25, 0xa9, 0x28, 0x4e, 0x78, 0x5a, 0x21, 0x3f, 0x42, 0x3b,
	0x79, 0x1c, 0x91, 0x62, 0x88, 0x5b, 0xcf, 0xbd, 0xee, 0x47, 0x6f, 0x61, 0xa4, 0x26, 0xcf, 0xa0,
	0x65, 0x46, 0x3e, 0xf9, 0xb0, 0x2c, 0x69, 0xb9, 0xb5, 0x51, 0x9e, 0xd5, 0xfc, 0xb6, 0x50, 0x2e,
	0xee, 0xe4, 0xde, 0x6a, 0x25, 0xd5, 0x2a, 0xbe, 0xe4, 0xba, 0xef, 0x15, 0x48, 0xb9, 0x87, 0x6c,
	0xe5, 0xba, 0xa9, 0x1e, 0xbc, 0xdf, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xee, 0x3b, 0xc6, 0x47,
	0x01, 0x0b, 0x00, 0x00,
}
